// <auto-generated />
using System;
using ApiWebExamenEf;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiWebExamenEf.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiWebExamenEf.Models.DetallePaS", b =>
                {
                    b.Property<Guid>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PersonaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("ServicioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DetalleId");

                    b.HasIndex("PersonaId");

                    b.HasIndex("ServicioId");

                    b.ToTable("DetallePaS", (string)null);
                });

            modelBuilder.Entity("ApiWebExamenEf.Models.Persona", b =>
                {
                    b.Property<string>("PersonaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NivelEstrato")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonaId");

                    b.ToTable("Persona", (string)null);
                });

            modelBuilder.Entity("ApiWebExamenEf.Models.Servicio", b =>
                {
                    b.Property<Guid>("ServicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescripcionServicio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NommbreServicio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ServicioId");

                    b.ToTable("Servicio", (string)null);
                });

            modelBuilder.Entity("ApiWebExamenEf.Models.DetallePaS", b =>
                {
                    b.HasOne("ApiWebExamenEf.Models.Persona", "Persona")
                        .WithMany("DetallePaSs")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiWebExamenEf.Models.Servicio", "Servicio")
                        .WithMany("DetallePaSs")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("ApiWebExamenEf.Models.Persona", b =>
                {
                    b.Navigation("DetallePaSs");
                });

            modelBuilder.Entity("ApiWebExamenEf.Models.Servicio", b =>
                {
                    b.Navigation("DetallePaSs");
                });
#pragma warning restore 612, 618
        }
    }
}
